# Generated by Django 3.2.12 on 2022-11-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dispMoviles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('memoria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('memoriaRam', models.IntegerField()),
                ('DiscoDuro', models.IntegerField()),
                ('DiscoSSD', models.IntegerField()),
                ('Procesador', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='licencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=50)),
                ('licencia', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
